### PR TITLE
feat: Add Local Copies of UNTP Credential Schemas in Tier Two Test Suite

### PR DESCRIPTION
**Pull request by ldhyen99**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by ashleythedeveloper** [comment]
@ldhyen99, it looks like you might have missed the VCDM properties for the Traceability events as I believe they are in the schema for 3.10. Not sure about the rest.

Testing Credential: transactionEvent
Version: v0.3.10
Path: /Users/admin/tier-three-testing/credentials/cotton/te.json
Result: FAIL
Warning: 
Additional property found: '@context'.
Additional property found: 'issuer'.
Additional property found: 'validFrom'.
Additional property found: 'credentialSubject'.
Error: 
/type field must be equal to constant.
/type/1 field must be equal to one of the allowed values. Allowed values: TransactionEvent, Event.

**Comment by ldhyen99** [comment]
> @ldhyen99, it looks like you might have missed the VCDM properties for the Traceability events as I believe they are in the schema for 3.10. Not sure about the rest.
> 
> Testing Credential: transactionEvent Version: v0.3.10 Path: /credentials/cotton/te.json Result: FAIL Warning: Additional property found: '@context'. Additional property found: 'issuer'. Additional property found: 'validFrom'. Additional property found: 'credentialSubject'. Error: /type field must be equal to constant. /type/1 field must be equal to one of the allowed values. Allowed values: TransactionEvent, Event.

Thanks for your comment. I'm curious about the data you checked with the transactionEvent schema version v0.3.10. I found the schema at [this link](https://jargon.sh/user/unece/traceabilityEvents/v/0.3.10), but I only found sample data for TransformationEvent and ObjectEvent in the instance file. Where can I find sample data for transactionEvent?

**Comment by ashleythedeveloper** [comment]
Yep, I created my own test data, which I'm using in the tier tree test suite.

``` javascript
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://vocabulary.uncefact.org/untp/dte/0.3.10",
  ],
  id: "https://cottonfarmers.com/credentials/transaction/raw-cotton-sale/654321",
  type: ["DigitalTraceabilityEvent", "VerifiableCredential"],
  issuer: {
    id: "did:web:cottonfarmers.example.com:54321",
    name: "Cotton Farmers Cooperative",
  },
  validFrom: "2024-09-15T10:00:00",
  credentialSubject: [
    {
      type: ["TransactionEvent", "Event"],
      id: "https://events.cottonfarmers.com/transaction/43f2a4af-9174-4e8a-a4be-b68a24259f0a",
      eventTime: "2024-09-15T10:00:00",
      action: "observe",
      bizStep: "https://ref.gs1.org/cbv/BizStep-consigning",
      disposition: "https://ref.gs1.org/cbv/Disp-active",
      bizLocation: "https://id.gs1.org/414/09456123456788",
      sourceParty: {
        id: "https://www.mca.gov.in/09456123456788",
        name: "Cotton Farmers Cooperative",
        registeredId: "091023456789",
        idScheme: {
          id: "https://www.mca.gov.in",
          name: "Ministry of Corporate Affairs",
        },
      },
      destinationParty: {
        id: "https://www.mca.gov.in/092012345678",
        name: "Ginning Mill Ltd.",
        registeredId: "092012345678",
        idScheme: {
          id: "https://www.mca.gov.in",
          name: "Ministry of Corporate Affairs",
        },
      },
      bizTransaction: "https://ref.gs1.org/cbv/BTT-inv",
      epcList: [
        {
          id: "https://id.gs1.org/01/00012345678910/10/COTTON20240901",
          name: "Raw Organic Cotton",
          registeredId: "COTTON20240901",
          idScheme: {
            id: "https://id.gs1.org/10",
            name: "Serial Number",
          },
        },
      ],
      quantityList: [
        {
          product: {
            type: ["Entity"],
            id: "https://id.gs1.org/01/00012345678910",
            name: "Raw Organic Cotton",
            registeredId: "00012345678910",
            idScheme: {
              id: "https://id.gs1.org/01",
            },
          },
          quantity: 1000,
          uom: "KGM",
        },
      ],
    },
  ],
}
```

**Comment by ldhyen99** [comment]
When I checked the https://jargon.sh/user/unece/traceabilityEvents/v/0.2.0 version, I saw that each event is separate. For example, the schema for a TransformationEvent should only include specific event fields without @context or issuer, which are usually related to credentials.

This is the result after I copy your object inside `credentialSubject`
image

```json
{
  "type": ["TransactionEvent", "Event"],
  "id": "https://events.cottonfarmers.com/transaction/43f2a4af-9174-4e8a-a4be-b68a24259f0a",
  "eventTime": "2024-09-15T10:00:00",
  "action": "observe",
  "bizStep": "https://ref.gs1.org/cbv/BizStep-consigning",
  "disposition": "https://ref.gs1.org/cbv/Disp-active",
  "bizLocation": "https://id.gs1.org/414/09456123456788",
  "sourceParty": {
    "id": "https://www.mca.gov.in/09456123456788",
    "name": "Cotton Farmers Cooperative",
    "registeredId": "091023456789",
    "idScheme": {
      "id": "https://www.mca.gov.in",
      "name": "Ministry of Corporate Affairs"
    }
  },
  "destinationParty": {
    "id": "https://www.mca.gov.in/092012345678",
    "name": "Ginning Mill Ltd.",
    "registeredId": "092012345678",
    "idScheme": {
      "id": "https://www.mca.gov.in",
      "name": "Ministry of Corporate Affairs"
    }
  },
  "bizTransaction": "https://ref.gs1.org/cbv/BTT-inv",
  "epcList": [
    {
      "id": "https://id.gs1.org/01/00012345678910/10/COTTON20240901",
      "name": "Raw Organic Cotton",
      "registeredId": "COTTON20240901",
      "idScheme": {
        "id": "https://id.gs1.org/10",
        "name": "Serial Number"
      }
    }
  ],
  "quantityList": [
    {
      "product": {
        "type": ["Entity"],
        "id": "https://id.gs1.org/01/00012345678910",
        "name": "Raw Organic Cotton",
        "registeredId": "00012345678910",
        "idScheme": {
          "id": "https://id.gs1.org/01"
        }
      },
      "quantity": 1000,
      "uom": "KGM"
    }
  ]
}
```

**Comment by huynguyen-hl** [comment]
I noticed that some events have been updated to v0.3.10 or v0.4.0. You could double check to ensure that all event schemas reflect the latest version.

**Review by namhoang1604 — DISMISSED** [review]
LGTM

**Comment by ashleythedeveloper** [comment]
@ldhyen99, for the test to be valid, the schema should include the VCDM properties. It looks like this was missed when defining the data model. This should be discussed with @onthebreeze, as I don't believe this is the intent. We need to ensure that the appropriate v2 VCDM properties are included within the schema in the next release.

**Review by huynguyen-hl — APPROVED** [review]

**Review by namhoang1604 — APPROVED** [review]

**Pull request merged**
