### PR TITLE
feat: copy schema versions past v0.4 in traceability events

### PR DESCRIPTION
**Pull request by ldhyen99**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

**Traceability Events (TEs)**
image

**DigitalProductPassport**
image

**Conformity Credential**
image

**DigitalFacilityRecord**
image

For testing, please copy the file below to `packages/untp-test-suite/credentials.json`:
```json
{
  "credentials": [
    {
      "type": "conformityCredential",
      "version": "v0.5.0",
      "dataPath": "credentials/conformityCredential/DigitalConformityCredential_instance-v0.5.0.json",
      "url": ""
    },
    {
      "type": "digitalFacilityRecord",
      "version": "v0.5.0",
      "dataPath": "credentials/digitalFacilityRecord/DigitalFacilityRecord_instance-v0.5.0.json",
      "url": ""
    },
    {
      "type": "productPassport",
      "version": "v0.5.0",
      "dataPath": "credentials/productPassport/DigitalProductPassport_instance-v0.5.0.json",
      "url": ""
    },
    {
      "type": "traceabilityEvents",
      "version": "v0.5.0",
      "dataPath": "credentials/traceabilityEvents/DigitalTraceabilityEvent_instance-v0.5.0.json",
      "url": ""
    }
  ]
}
```
and run `yarn run untp test`

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by ashleythedeveloper** [comment]
@ldhyen99, @namhoang1604, it seems that all Traceability Events defined within the config file are currently displayed as traceabilityEvents, which could make debugging more challenging. What are your thoughts?

**Comment by namhoang1604** [comment]
> @ldhyen99, @namhoang1604, it seems that all Traceability Events defined within the config file are currently displayed as traceabilityEvents, which could make debugging more challenging. What are your thoughts?

I think it depends on the configuration file, if we want to test the details of the event schema, we can add the event schema in the configuration file.

**Review by namhoang1604 — APPROVED** [review]

**Comment by ashleythedeveloper** [comment]
> > @ldhyen99, @namhoang1604, it seems that all Traceability Events defined within the config file are currently displayed as traceabilityEvents, which could make debugging more challenging. What are your thoughts?
> 
> I think it depends on the configuration file, if we want to test the details of the event schema, we can add the event schema in the configuration file.

Right, but in doing so for each traceability event would yield a similar result as the screenshot provided by Yen.
377695809-49a26524-1a23-4451-9ee3-242ea66a0cbc

I guess we can use the error output.

**Comment by ldhyen99** [comment]
> I guess we can use the path from the error output.

Yep, which means we'll add a column as Path and the value of it will credentials/DigitalConformityCredential_instance-v0.5.0.json, is it correct?

**Comment by huynguyen-hl** [comment]
I think we should add additional schema events that belong to `traceabilityEvents`. What do you think?

**Comment by ldhyen99** [comment]
> I think we should add additional schema events that belong to `traceabilityEvents`. What do you think?

After discussing with team, maintaining a single Traceability Events schema reduces complexity and simplifies automation, though it adds friction when interpreting test results. Separating schemas makes debugging easier but increases maintenance effort and the risk of mistakes. For now, the single schema approach is sufficient, as it correctly validates event credentials and ensures tests fail when incompatible properties are used.

**Review by huynguyen-hl — APPROVED** [review]

**Pull request merged**
