### PR TITLE
feat: add dpp render template 0.5.0

### PR DESCRIPTION
**Pull request by huynguyen-hl**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This is a Handlebar template that accurately reflects the new v0.5 DPP design.

## Mobile & Desktop Screenshots/Recordings

Mobile UI:
image
image
image
image

Desktop UI:
image
image
image
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by ldhyen99** [comment]
Hi, can you check again this UI on the desktop
image

I see in UI, which after "by" it should be in one line 
image

**Comment by ldhyen99** [comment]
Should we put this text on one line?
image

image

**Comment by ldhyen99** [comment]
Can you help me check the History block? I can not see any data on credentialSubject.traceabilityInformation when using https://jargon.sh/user/unece/DigitalProductPassport/v/0.5.0/artefacts/jsonSchemas/DigitalProductPassport_instance.json?class=DigitalProductPassport_instance

image

The UI:
image

Thanks

**Comment by ldhyen99** [comment]
Should we format date following the design?
image

The UI
image

**Comment by huynguyen-hl** [comment]
@ldhyen99

> Hi, can you check again this UI on the desktop image
> 
> I see in UI, which after "by" it should be in one line image

This was my mistake when implementing the UI. I’ve already fixed it in the latest commit. Thanks for pointing it out.

---

> Should we put this text on one line? image
> 
> image

Since your text is a bit long, it will move to the next line. I’ll adjust the text-decoration to fit the text length. Thanks for bringing this up.

---

> Can you help me check the History block? I can not see any data on credentialSubject.traceabilityInformation when using https://jargon.sh/user/unece/DigitalProductPassport/v/0.5.0/artefacts/jsonSchemas/DigitalProductPassport_instance.json?class=DigitalProductPassport_instance
> 
> image
> The UI: image
> 
> Thanks

This was my error when implementing this UI. The designer and I didn’t realize that the data model had changed. I’ll update the data mapping for this UI accordingly. Thanks for raising this.

---

> Should we format date following the design? image
> 
> The UI image

I don’t believe we can format dates directly in a Handlebars (hbs) template, as it doesn’t support that feature. To my knowledge, there isn’t a solution for formatting dates in an hbs template. If you have any ideas, please feel free to share, I’d appreciate it. Thanks for bringing this up.

---

> Hi, can you add the ">" in `Product composition` image
> 
> as the design image

This is from an older design. We discussed it in this conversation: https://gosource.slack.com/archives/C05R3FRGA3U/p1729236646889239?thread_ts=1729158343.107749&cid=C05R3FRGA3U. 

The DPP design hasn’t been updated to reflect this conversation.

**Review by namhoang1604 — APPROVED** [review]

**Pull request merged**
